services:
  - type: web
    name: ahrori-ai-bot
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        value: 8925416268:AAFhSrfU4zCMYQbT_VKxcJTkdUy-acb06qE
      - key: GEMINI_API_KEY
        value: AQ.Ab8RN6IizhgjzEFjdHxI9BJ4H7mfH_EUwlNyrZzTOtDLjeDA9A
      - key: ADMIN_ID
        value: "8388288136"
